"""Update reports table ownership

Revision ID: 3e1fdafd6344
Revises: cab05be302d4
Create Date: 2026-02-22 14:04:37.374679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1fdafd6344'
down_revision: Union[str, Sequence[str], None] = 'cab05be302d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('project_id', sa.UUID(), nullable=False), schema='app')
    op.drop_constraint(op.f('reports_run_id_fkey'), 'reports', schema='app', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_column('reports', 'run_id', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False), schema='app')
    op.drop_constraint(None, 'reports', schema='app', type_='foreignkey')
    op.create_foreign_key(op.f('reports_run_id_fkey'), 'reports', 'runs', ['run_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.drop_column('reports', 'project_id', schema='app')
    # ### end Alembic commands ###
