"""create agent_runs table

Revision ID: 4b82ca5b10a3
Revises: 3e1fdafd6344
Create Date: 2026-04-05 00:34:00.223820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b82ca5b10a3'
down_revision: Union[str, Sequence[str], None] = '3e1fdafd6344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_runs', schema='app')
    # ### end Alembic commands ###
