"""add report_id to agent_runs

Revision ID: 62bb4a93e5b9
Revises: 4b82ca5b10a3
Create Date: 2026-04-05 01:07:11.113944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62bb4a93e5b9'
down_revision: Union[str, Sequence[str], None] = '4b82ca5b10a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('report_id', sa.UUID(), nullable=True), schema='app')
    op.create_foreign_key(None, 'agent_runs', 'reports', ['report_id'], ['id'], source_schema='app', referent_schema='app', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_runs', schema='app', type_='foreignkey')
    op.drop_column('agent_runs', 'report_id', schema='app')
    # ### end Alembic commands ###
