"""Initial database setup

Revision ID: cab05be302d4
Revises: 
Create Date: 2026-02-14 14:17:24.597582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab05be302d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_status', sa.Enum('ACTIVE', 'ARCHIVED', name='project_status_enum', schema='app'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_type', sa.Enum('IP', 'CIDR', 'DOMAIN', 'URL', name='target_type_enum', schema='app'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_type', sa.Enum('OSINT', 'SCAN', 'EXPLOIT', 'STRESS_TEST', name='run_type_enum', schema='app'), nullable=True),
    sa.Column('purpose', sa.Enum('PRIMARY', 'SUBTASK', 'ENRICHMENT', 'RETRY', 'VALIDATION', name='run_purpose_enum', schema='app'), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='run_status_enum', schema='app'), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_version', sa.String(length=64), nullable=True),
    sa.Column('raw_command', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_format', sa.Enum('BINARY', 'FILE', 'TEXT', 'JSON', 'XML', 'CSV', name='run_output_format_enum', schema='app'), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['app.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['app.targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finding_type', sa.Enum('VULNERABILITY', 'MISCONFIGURATION', 'CREDENTIAL', 'INFORMATION', name='finding_type_enum', schema='app'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finding_severity_enum', schema='app'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['app.runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('report_format', sa.Enum('PDF', 'HTML', 'JSON', 'MARKDOWN', name='report_format_enum', schema='app'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['app.runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports', schema='app')
    op.drop_table('findings', schema='app')
    op.drop_table('runs', schema='app')
    op.drop_table('targets', schema='app')
    op.drop_table('projects', schema='app')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
